### ISSUE TITLE
nonut rizz not working

### ISSUE THREAD

**Issue by VeryElegantBread** [Brainrotlang/brainrot#23]
the sigma lines be yapping about `Error: syntax error at line 2`

```
skibidi main {
	nonut rizz h = 10;
	bussin 0;
}
```

**Comment by araujo88** [comment]
Bruh, it seems the `nonut` and `nut` keywords were not implemented. I'll prioritize that on my daily grinding. No cap.

**Comment by araujo88** [comment]
Fixed in https://github.com/Brainrotlang/brainrot/pull/24. Please update with the latest version.
